import Header from "./Header";
import type { ReactNode } from "react";
import Head from "next/head";
import Footer from "./Footer";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="flex min-h-screen flex-col bg-base-200">
      <Head>
        <title>T3 for web3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="min-h-screen">{children}</main>
      <Footer />
    </div>
  );
}
