/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */ 

export const networkMapping ={
  "hardhat": {
    "MrCryptoMock": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "RacksProjectManager": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "HolderValidation": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "ERC20Mock": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "TransparentUpgradeableProxy": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    "ProxyAdmin": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  },
  "goerli": {
    "MrCryptoMock": "0xC80b8456976ec3E0fb63B5D0c417E46f240cBf1c",
    "Lock": "0x2DB124Db572F006A3698A296B0AFa0D3226Cbf9a"
  },
  "localhost": {
    "MrCryptoMock": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "ERC20Mock": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "RacksProjectManager": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "HolderValidation": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "TransparentUpgradeableProxy": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    "ProxyAdmin": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  }
} as const;